### ISSUE TITLE
[IDEA] Better Minecarts for 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [xR4YM0ND/RAYs-3D-Rails#2]
add support for 3D rails from Xannosz's Better minecarts (including dead end) for Minecraft 1.20.1
CurseForge page: https://www.curseforge.com/minecraft/mc-mods/xannoszs-better-minecarts

**Comment by xR4YM0ND** [comment]
Added Support in v1.2

https://legacy.curseforge.com/minecraft/texture-packs/rays-3d-rails/files/4773862
https://modrinth.com/resourcepack/rays-3d-rails/version/1.2

If you find any bugs or if your unhappy with the textures, let me know

~ Ray
