### ISSUE TITLE
[BUG] Powered rail hill shows a missing model

### ISSUE THREAD

**Issue by vinnyg0621** [xR4YM0ND/RAYs-3D-Rails#3]
**Describe the bug**
on my Minecraft rollercoaster, I found this:
![2023-09-29_17 35 47](https://github.com/xR4YM0ND/RAYs-3D-Rails/assets/57818441/d0ecd83c-b9e4-440b-936c-4d55b1398691)
![2023-09-29_17 36 18](https://github.com/xR4YM0ND/RAYs-3D-Rails/assets/57818441/00bf6092-7023-4c5f-8767-cd5b55364389)

**Comment by xR4YM0ND** [comment]
Thank you for reporting!

Will get fixed in v1.3 & some other modded powered rails issues

**Comment by xR4YM0ND** [comment]
Fixed in version 1.3
