### ISSUE TITLE
rail item going into ground [BUG]

### ISSUE THREAD

**Issue by vaillantoine** [xR4YM0ND/RAYs-3D-Rails#4]
**Describe the bug**
When the item is dropped, the texture goes into the ground during the item mouvement up and down (![2023-12-10_18 07 01](https://github.com/xR4YM0ND/RAYs-3D-Rails/assets/95367792/445993ec-07eb-469c-bbff-0f74e6012cc6) and ![2023-12-10_18 07 02](https://github.com/xR4YM0ND/RAYs-3D-Rails/assets/95367792/70838333-9840-4f6d-a3a5-66f97f309567)).
It can be fixed as show in this screenshot: ![Capture d'écran 2023-12-10 181126](https://github.com/xR4YM0ND/RAYs-3D-Rails/assets/95367792/00a4697c-aa00-443b-8140-b8c849d3e002).

**Comment by xR4YM0ND** [comment]
Fixed in version 1.5
