### ISSUE TITLE
[Feature Request] Add a texture for the controller rail on Create mod (please ; - ;)

### ISSUE THREAD

**Issue by OlaPessoa** [xR4YM0ND/RAYs-3D-Rails#6]
**Describe your idea in depth.**
in depth my idea has no depth, it is only what i said in the title, you're welcome for the in depth description.

**Comment by xR4YM0ND** [comment]
Added Create support in [1.7](https://modrinth.com/resourcepack/rays-3d-rails/version/1.7)
